### ISSUE TITLE
KeyCloak support

### ISSUE THREAD

**Issue by jharmison-redhat** [jharmison-redhat/sonarqube-operator#3]
Need to be able to integrate with KeyCloak at the operator level, via appropriate spec entries at the CRD and the necessary Ansible to complete the configuration.

**Comment by andykrohg** [comment]
It should be noted on this that at least two other tools in the chain at the moment (Jenkins and ArgoCD) presently integrate with KeyCloak by way of OpenShift OAuth, since OCP itself is an OAuth client to the SSO instance.

**Comment by jharmison-redhat** [comment]
Was talking with @akochnev earlier - he's going to see what a good route for us to go is. Can't @ him on here for real as he hasn't accepted invite yet, but I believe he's familiar with those, yes?

**Comment by andykrohg** [comment]
I implemented the one for Argo and I'm pretty sure Jay did Jenkins, but for reference, the Argo CR takes an argument to use [dex](https://github.com/dexidp/dex) (which is its own deployment/pod) to facilitate oauth, since you can't configure it directly in the app itself. The same is true for Nexus (though SAML is available in the paid version 👎 ), and during testing I injected an oauth-proxy sidecar.

**Comment by jharmison-redhat** [comment]
See: https://github.com/RedHatGov/sonarqube-operator/issues/2
